{
 "title": "Quorum Store",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "PULLED_TXNS_COUNT",
   "type": "timeseries",
   "description": "Count of the pulled txns.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(quorum_store_pulled_txn_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PULLED_EMPTY_TXNS_COUNT",
   "type": "timeseries",
   "description": "Count of the pulled empty txns.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(quorum_store_pulled_empty_txn_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EXCEEDED_STORAGE_QUOTA_COUNT",
   "type": "timeseries",
   "description": "Count of the exceeded storage quota.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(quorum_store_exceeded_storage_quota_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "BATCH_CREATION_DURATION",
   "type": "timeseries",
   "description": "Histogram of the time durations for batch creation.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(quorum_store_batch_creation_duration_sum[$__rate_interval]) / rate(quorum_store_batch_creation_duration_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EMPTY_BATCH_CREATION_DURATION",
   "type": "timeseries",
   "description": "Histogram of the time durations for empty batch creation.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "rate(quorum_store_empty_batch_creation_duration_sum[$__rate_interval]) / rate(quorum_store_empty_batch_creation_duration_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BATCH_TO_POS_DURATION",
   "type": "timeseries",
   "description": "Histogram of the time durations from batch creation to PoS creation.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "rate(quorum_store_batch_to_PoS_duration_sum[$__rate_interval]) / rate(quorum_store_batch_to_PoS_duration_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Quorum Store Measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "NUM_BATCH_PER_BLOCK",
   "type": "timeseries",
   "description": "Histogram for the number of batches per (committed) blocks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(quorum_store_num_batch_per_block_sum[$__rate_interval]) / rate(quorum_store_num_batch_per_block_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NUM_TXN_PER_BATCH",
   "type": "timeseries",
   "description": "Histogram for the number of transactions per batch.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(quorum_store_num_txn_per_batch_sum[$__rate_interval]) / rate(quorum_store_num_txn_per_batch_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CREATED_BATCHES_COUNT",
   "type": "timeseries",
   "description": "Count of the created batches since last restart.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(quorum_store_created_batch_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CREATED_EMPTY_BATCHES_COUNT",
   "type": "timeseries",
   "description": "Count of the created empty batches since last restart.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(quorum_store_created_empty_batch_count[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "DELIVERED_BATCHES_COUNT",
   "type": "timeseries",
   "description": "Count of the created batches since last restart.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(quorum_store_delivered_batch_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MISSED_BATCHES_COUNT",
   "type": "timeseries",
   "description": "Count of the missed batches when execute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(quorum_store_missed_batch_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POS_COUNT",
   "type": "timeseries",
   "description": "Count of the proof-of-store (PoS) gathered since last restart.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(quorum_store_PoS_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TIMEOUT_BATCHES_COUNT",
   "type": "timeseries",
   "description": "Count of the timeout batches at the sender side.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "rate(quorum_store_timeout_batch_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EXPIRED_BATCH_FRAGMENTS_COUNT",
   "type": "timeseries",
   "description": "Count of the expired batch fragments at the receiver side.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(quorum_store_expired_batch_fragments_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MISSED_BATCH_FRAGMENTS_COUNT",
   "type": "timeseries",
   "description": "Count of the missed batch fragments at the receiver side.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "rate(quorum_store_missed_batch_fragments_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}